// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "TypeScript Guidebook",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/withastro/starlight",
        },
      ],
      components: {
        Hero: "./src/components/Hero.astro",
      },
      customCss: [
        "./src/styles/custom.css",
      ],
      sidebar: [
        {
          label: "BAB 0 — Pengenalan",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab0/introduction/" },
            { label: "Selamat Datang", link: "/bab0/selamat-datang/" },
            { label: "Cara Menggunakan Guidebook", link: "/bab0/cara-menggunakan-guidebook/" },
            { label: "Apa itu Programming", link: "/bab0/apa-itu-programming/" },
            { label: "Computational Thinking", link: "/bab0/computational-thinking/" },
            { label: "Mengenal Dunia Web", link: "/bab0/mengenal-dunia-web/" },
            { label: "HTML, CSS, JavaScript", link: "/bab0/html-css-javascript/" },
            { label: "Mengapa TypeScript", link: "/bab0/mengapa-typescript/" },
            { label: "JavaScript vs TypeScript", link: "/bab0/javascript-vs-typescript/" },
            { label: "Workflow Developer Modern", link: "/bab0/workflow-developer-modern/" },
            { label: "Persiapan Software", link: "/bab0/persiapan-software/" },
            { label: "Install Node.js", link: "/bab0/install-nodejs/" },
            { label: "Install VS Code", link: "/bab0/install-vscode/" },
            { label: "Install TypeScript", link: "/bab0/install-typescript/" },
            { label: "Install TSX", link: "/bab0/install-tsx/" },
            { label: "Membuat Project Pertama", link: "/bab0/membuat-project-pertama/" },
            { label: "Struktur Project", link: "/bab0/struktur-project/" },
            { label: "Program Pertama", link: "/bab0/program-pertama/" },
            { label: "Error Corner", link: "/bab0/error-corner/" },
            { label: "Ringkasan", link: "/bab0/ringkasan/" },
          ],
        },
        {
          label: "BAB 1 — Variabel & Tipe Data",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab1/introduction/" },
            { label: "Apa itu Variabel", link: "/bab1/apa-itu-variabel/" },
            { label: "Deklarasi Variabel", link: "/bab1/deklarasi-variabel/" },
            { label: "let vs const", link: "/bab1/let-vs-const/" },
            { label: "Aturan Penamaan Variabel", link: "/bab1/aturan-penamaan-variabel/" },
            { label: "Tipe Data", link: "/bab1/tipe-data/" },
            { label: "number", link: "/bab1/number/" },
            { label: "string", link: "/bab1/string/" },
            { label: "boolean", link: "/bab1/boolean/" },
            { label: "null dan undefined", link: "/bab1/null-dan-undefined/" },
            { label: "bigint", link: "/bab1/bigint/" },
            { label: "symbol", link: "/bab1/symbol/" },
            { label: "any", link: "/bab1/any/" },
            { label: "unknown", link: "/bab1/unknown/" },
            { label: "never", link: "/bab1/never/" },
            { label: "Type Inference", link: "/bab1/type-inference/" },
            { label: "Literal Type", link: "/bab1/literal-type/" },
            { label: "Template Literal", link: "/bab1/template-literal/" },
            { label: "Studi Kasus", link: "/bab1/studi-kasus/" },
            { label: "Mini Project", link: "/bab1/mini-project/" },
            { label: "Challenge", link: "/bab1/challenge/" },
            { label: "Error Corner", link: "/bab1/error-corner/" },
            { label: "Ringkasan", link: "/bab1/ringkasan/" },
          ],
        },
        {
          label: "BAB 2 — Operator & Percabangan",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab2/introduction/" },
            { label: "Apa itu Operator", link: "/bab2/apa-itu-operator/" },
            { label: "Operator Aritmatika", link: "/bab2/operator-aritmatika/" },
            { label: "Operator Penugasan", link: "/bab2/operator-penugasan/" },
            { label: "Operator Perbandingan", link: "/bab2/operator-perbandingan/" },
            { label: "Operator Logika", link: "/bab2/operator-logika/" },
            { label: "Operator Unary", link: "/bab2/operator-unary/" },
            { label: "Operator Nullish", link: "/bab2/operator-nullish/" },
            { label: "Prioritas Operator", link: "/bab2/prioritas-operator/" },
            { label: "Apa itu Percabangan", link: "/bab2/apa-itu-percabangan/" },
            { label: "if", link: "/bab2/if/" },
            { label: "if...else", link: "/bab2/if-else/" },
            { label: "else if", link: "/bab2/else-if/" },
            { label: "Nested if", link: "/bab2/nested-if/" },
            { label: "switch", link: "/bab2/switch/" },
            { label: "Ternary Operator", link: "/bab2/ternary-operator/" },
            { label: "Studi Kasus", link: "/bab2/studi-kasus/" },
            { label: "Mini Project", link: "/bab2/mini-project/" },
            { label: "Challenge", link: "/bab2/challenge/" },
            { label: "Error Corner", link: "/bab2/error-corner/" },
            { label: "Ringkasan", link: "/bab2/ringkasan/" },
          ],
        },
        {
          label: "BAB 3 — Perulangan",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab3/introduction/" },
            { label: "Apa itu Perulangan", link: "/bab3/apa-itu-perulangan/" },
            { label: "for", link: "/bab3/for/" },
            { label: "while", link: "/bab3/while/" },
            { label: "do...while", link: "/bab3/do-while/" },
            { label: "for...of", link: "/bab3/for-of/" },
            { label: "for...in", link: "/bab3/for-in/" },
            { label: "break & continue", link: "/bab3/break-continue/" },
            { label: "Nested Loop", link: "/bab3/nested-loop/" },
            { label: "Studi Kasus", link: "/bab3/studi-kasus/" },
            { label: "Mini Project", link: "/bab3/mini-project/" },
            { label: "Challenge", link: "/bab3/challenge/" },
            { label: "Error Corner", link: "/bab3/error-corner/" },
            { label: "Ringkasan", link: "/bab3/ringkasan/" },
          ],
        },
        {
          label: "BAB 4 — Function",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab4/introduction/" },
            { label: "Mengapa Function", link: "/bab4/mengapa-function/" },
            { label: "Membuat Function", link: "/bab4/membuat-function/" },
            { label: "Memanggil Function", link: "/bab4/memanggil-function/" },
            { label: "Parameter dan Argument", link: "/bab4/parameter-dan-argument/" },
            { label: "Multiple Parameter", link: "/bab4/multiple-parameter/" },
            { label: "Default Parameter", link: "/bab4/default-parameter/" },
            { label: "Optional Parameter", link: "/bab4/optional-parameter/" },
            { label: "Rest Parameter", link: "/bab4/rest-parameter/" },
            { label: "Return Value", link: "/bab4/return-value/" },
            { label: "Scope", link: "/bab4/scope/" },
            { label: "Studi Kasus", link: "/bab4/studi-kasus/" },
            { label: "Mini Project", link: "/bab4/mini-project/" },
            { label: "Challenge", link: "/bab4/challenge/" },
            { label: "Error Corner", link: "/bab4/error-corner/" },
            { label: "Ringkasan", link: "/bab4/ringkasan/" },
          ],
        },
        {
          label: "BAB 5 — Array",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab5/introduction/" },
            { label: "Apa itu Array", link: "/bab5/apa-itu-array/" },
            { label: "Membuat Array", link: "/bab5/membuat-array/" },
            { label: "Mengakses Data Array", link: "/bab5/mengakses-data-array/" },
            { label: "Mengubah Data Array", link: "/bab5/mengubah-data-array/" },
            { label: "Panjang Array", link: "/bab5/panjang-array/" },
            { label: "push & pop", link: "/bab5/push-pop/" },
            { label: "shift & unshift", link: "/bab5/shift-unshift/" },
            { label: "splice & slice", link: "/bab5/splice-slice/" },
            { label: "concat", link: "/bab5/concat/" },
            { label: "reverse", link: "/bab5/reverse/" },
            { label: "sort", link: "/bab5/sort/" },
            { label: "includes & indexOf", link: "/bab5/includes-indexof/" },
            { label: "find", link: "/bab5/find/" },
            { label: "filter", link: "/bab5/filter/" },
            { label: "map", link: "/bab5/map/" },
            { label: "reduce", link: "/bab5/reduce/" },
            { label: "Iterasi Array", link: "/bab5/iterasi-array/" },
            { label: "Studi Kasus", link: "/bab5/studi-kasus/" },
            { label: "Mini Project", link: "/bab5/mini-project/" },
            { label: "Challenge", link: "/bab5/challenge/" },
            { label: "Error Corner", link: "/bab5/error-corner/" },
            { label: "Ringkasan", link: "/bab5/ringkasan/" },
          ],
        },
        {
          label: "BAB 6 — Object",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab6/introduction/" },
            { label: "Mengapa Object", link: "/bab6/mengapa-object/" },
            { label: "Apa itu Object", link: "/bab6/apa-itu-object/" },
            { label: "Membuat Object", link: "/bab6/membuat-object/" },
            { label: "Property", link: "/bab6/property/" },
            { label: "Mengakses Property", link: "/bab6/mengakses-property/" },
            { label: "Mengubah Property", link: "/bab6/mengubah-property/" },
            { label: "Menambah Property", link: "/bab6/menambah-property/" },
            { label: "Menghapus Property", link: "/bab6/menghapus-property/" },
            { label: "Nested Object", link: "/bab6/nested-object/" },
            { label: "Array of Object", link: "/bab6/array-of-object/" },
            { label: "Destructuring", link: "/bab6/destructuring/" },
            { label: "Spread Operator", link: "/bab6/spread-operator/" },
            { label: "Optional Chaining", link: "/bab6/optional-chaining/" },
            { label: "Nullish Coalescing", link: "/bab6/nullish-coalescing/" },
            { label: "Studi Kasus", link: "/bab6/studi-kasus/" },
            { label: "Mini Project", link: "/bab6/mini-project/" },
            { label: "Challenge", link: "/bab6/challenge/" },
            { label: "Error Corner", link: "/bab6/error-corner/" },
            { label: "Ringkasan", link: "/bab6/ringkasan/" },
          ],
        },
        {
          label: "BAB 7 — Interface & Type",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab7/introduction/" },
            { label: "Mengapa Interface", link: "/bab7/mengapa-interface/" },
            { label: "Apa itu Interface", link: "/bab7/apa-itu-interface/" },
            { label: "Membuat Interface", link: "/bab7/membuat-interface/" },
            { label: "Interface pada Object", link: "/bab7/interface-pada-object/" },
            { label: "Interface pada Function", link: "/bab7/interface-pada-function/" },
            { label: "Optional Property", link: "/bab7/optional-property/" },
            { label: "Readonly Property", link: "/bab7/readonly-property/" },
            { label: "Extend Interface", link: "/bab7/extend-interface/" },
            { label: "Apa itu Type Alias", link: "/bab7/apa-itu-type-alias/" },
            { label: "Membuat Type Alias", link: "/bab7/membuat-type-alias/" },
            { label: "Interface vs Type", link: "/bab7/interface-vs-type/" },
            { label: "Union Type", link: "/bab7/union-type/" },
            { label: "Intersection Type", link: "/bab7/intersection-type/" },
            { label: "Literal Type", link: "/bab7/literal-type/" },
            { label: "Enum", link: "/bab7/enum/" },
            { label: "Studi Kasus", link: "/bab7/studi-kasus/" },
            { label: "Mini Project", link: "/bab7/mini-project/" },
            { label: "Challenge", link: "/bab7/challenge/" },
            { label: "Error Corner", link: "/bab7/error-corner/" },
            { label: "Ringkasan", link: "/bab7/ringkasan/" },
          ],
        },
        {
          label: "BAB 8 — OOP & Class",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab8/introduction/" },
            { label: "Mengapa OOP", link: "/bab8/mengapa-oop/" },
            { label: "Apa itu OOP", link: "/bab8/apa-itu-oop/" },
            { label: "Apa itu Class", link: "/bab8/apa-itu-class/" },
            { label: "Membuat Class", link: "/bab8/membuat-class/" },
            { label: "Property", link: "/bab8/property/" },
            { label: "Method", link: "/bab8/method/" },
            { label: "Constructor", link: "/bab8/constructor/" },
            { label: "Membuat Object", link: "/bab8/membuat-object/" },
            { label: "this Keyword", link: "/bab8/this-keyword/" },
            { label: "Access Modifier", link: "/bab8/access-modifier/" },
            { label: "Getter & Setter", link: "/bab8/getter-setter/" },
            { label: "Static Member", link: "/bab8/static-member/" },
            { label: "Inheritance", link: "/bab8/inheritance/" },
            { label: "Encapsulation", link: "/bab8/encapsulation/" },
            { label: "Polymorphism", link: "/bab8/polymorphism/" },
            { label: "Abstract Class", link: "/bab8/abstract-class/" },
            { label: "Studi Kasus", link: "/bab8/studi-kasus/" },
            { label: "Mini Project", link: "/bab8/mini-project/" },
            { label: "Challenge", link: "/bab8/challenge/" },
            { label: "Error Corner", link: "/bab8/error-corner/" },
            { label: "Ringkasan", link: "/bab8/ringkasan/" },
          ],
        },
        {
          label: "BAB 9 — Generic & Utility Types",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab9/introduction/" },
            { label: "Mengapa Generic", link: "/bab9/mengapa-generic/" },
            { label: "Apa itu Generic", link: "/bab9/apa-itu-generic/" },
            { label: "Generic Function", link: "/bab9/generic-function/" },
            { label: "Generic Interface", link: "/bab9/generic-interface/" },
            { label: "Generic Class", link: "/bab9/generic-class/" },
            { label: "Generic Type", link: "/bab9/generic-type/" },
            { label: "Generic Constraint", link: "/bab9/generic-constraint/" },
            { label: "Apa itu Utility Type", link: "/bab9/apa-itu-utility-type/" },
            { label: "Partial", link: "/bab9/partial/" },
            { label: "Required", link: "/bab9/required/" },
            { label: "Readonly", link: "/bab9/readonly/" },
            { label: "Record", link: "/bab9/record/" },
            { label: "Pick", link: "/bab9/pick/" },
            { label: "Omit", link: "/bab9/omit/" },
            { label: "Exclude", link: "/bab9/exclude/" },
            { label: "Extract", link: "/bab9/extract/" },
            { label: "Parameters", link: "/bab9/parameters/" },
            { label: "ReturnType", link: "/bab9/returntype/" },
            { label: "keyof", link: "/bab9/keyof/" },
            { label: "typeof", link: "/bab9/typeof/" },
            { label: "Studi Kasus", link: "/bab9/studi-kasus/" },
            { label: "Mini Project", link: "/bab9/mini-project/" },
            { label: "Challenge", link: "/bab9/challenge/" },
            { label: "Error Corner", link: "/bab9/error-corner/" },
            { label: "Ringkasan", link: "/bab9/ringkasan/" },
          ],
        },
        {
          label: "BAB 10 — Async & Module",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab10/introduction/" },
            { label: "Mengapa Asynchronous", link: "/bab10/mengapa-asynchronous/" },
            { label: "Apa itu Asynchronous", link: "/bab10/apa-itu-asynchronous/" },
            { label: "Synchronous vs Asynchronous", link: "/bab10/synchronous-vs-asynchronous/" },
            { label: "Callback", link: "/bab10/callback/" },
            { label: "Promise", link: "/bab10/promise/" },
            { label: "async/await", link: "/bab10/async-await/" },
            { label: "Error Handling Async", link: "/bab10/error-handling-async/" },
            { label: "Fetch API", link: "/bab10/fetch-api/" },
            { label: "Apa itu Module", link: "/bab10/apa-itu-module/" },
            { label: "Export & Import", link: "/bab10/export-import/" },
            { label: "Named Export", link: "/bab10/named-export/" },
            { label: "Default Export", link: "/bab10/default-export/" },
            { label: "Re-export", link: "/bab10/re-export/" },
            { label: "Namespace", link: "/bab10/namespace/" },
            { label: "Studi Kasus", link: "/bab10/studi-kasus/" },
            { label: "Mini Project", link: "/bab10/mini-project/" },
            { label: "Challenge", link: "/bab10/challenge/" },
            { label: "Error Corner", link: "/bab10/error-corner/" },
            { label: "Ringkasan", link: "/bab10/ringkasan/" },
          ],
        },
        {
          label: "BAB 11 — Project Nyata",
          collapsed: true,
          items: [
            { label: "Introduction",              link: "/bab11/introduction/" },
            { label: "Briefing Project",          link: "/bab11/briefing-project/" },
            { label: "Setup Awal",                link: "/bab11/setup-awal/" },
            { label: "Implementasi Model",        link: "/bab11/implementasi-model/" },
            { label: "Implementasi Interface",    link: "/bab11/implementasi-interface/" },
            { label: "Implementasi Class",        link: "/bab11/implementasi-class/" },
            { label: "Implementasi Repository",   link: "/bab11/implementasi-repository/" },
            { label: "Implementasi Service",      link: "/bab11/implementasi-service/" },
            { label: "Implementasi Helper",       link: "/bab11/implementasi-helper/" },
            { label: "Implementasi main.ts",      link: "/bab11/implementasi-main/" },
            { label: "Testing",                   link: "/bab11/testing/" },
            { label: "Debugging",                 link: "/bab11/debugging/" },
            { label: "Best Practice",             link: "/bab11/best-practice/" },
            { label: "Studi Kasus",               link: "/bab11/studi-kasus/" },
            { label: "Challenge",                 link: "/bab11/challenge/" },
            { label: "Pengembangan Lanjutan",     link: "/bab11/pengembangan-lanjutan/" },
            { label: "Ringkasan",                 link: "/bab11/ringkasan/" },
          ],
        },
        {
          label: "BAB 12 — Best Practice TypeScript",
          collapsed: true,
          items: [
            { label: "Introduction",             link: "/bab12/introduction/" },
            { label: "Mengapa Best Practice",    link: "/bab12/mengapa-best-practice/" },
            { label: "Clean Code",               link: "/bab12/clean-code/" },
            { label: "Naming Convention",        link: "/bab12/naming-convention/" },
            { label: "Struktur Folder",          link: "/bab12/struktur-folder/" },
            { label: "Modular Programming",      link: "/bab12/modular-programming/" },
            { label: "DRY Principle",            link: "/bab12/dry-principle/" },
            { label: "KISS Principle",           link: "/bab12/kiss-principle/" },
            { label: "SOLID Introduction",       link: "/bab12/solid-introduction/" },
            { label: "ESLint",                   link: "/bab12/eslint/" },
            { label: "Prettier",                 link: "/bab12/prettier/" },
            { label: "tsconfig.json",            link: "/bab12/tsconfig/" },
            { label: "package.json",             link: "/bab12/package-json/" },
            { label: "Environment Variable",     link: "/bab12/environment-variable/" },
            { label: "Debugging",                link: "/bab12/debugging/" },
            { label: "Git Workflow",             link: "/bab12/git-workflow/" },
            { label: "README",                   link: "/bab12/readme/" },
            { label: "Studi Kasus",              link: "/bab12/studi-kasus/" },
            { label: "Mini Project",             link: "/bab12/mini-project/" },
            { label: "Challenge",                link: "/bab12/challenge/" },
            { label: "Ringkasan",                link: "/bab12/ringkasan/" },
          ],
        },
        {
          label: "BAB 13 — TS Ecosystem & Career",
          collapsed: true,
          items: [
            { label: "Introduction",             link: "/bab13/introduction/" },
            { label: "TypeScript Ecosystem",     link: "/bab13/typescript-ecosystem/" },
            { label: "Frontend Roadmap",         link: "/bab13/frontend-roadmap/" },
            { label: "Backend Roadmap",          link: "/bab13/backend-roadmap/" },
            { label: "Fullstack Roadmap",        link: "/bab13/fullstack-roadmap/" },
            { label: "Mobile Development",       link: "/bab13/mobile-development/" },
            { label: "Desktop Development",      link: "/bab13/desktop-development/" },
            { label: "Framework Modern",         link: "/bab13/framework-modern/" },
            { label: "Database Ecosystem",       link: "/bab13/database-ecosystem/" },
            { label: "Testing",                  link: "/bab13/testing/" },
            { label: "Deployment",               link: "/bab13/deployment/" },
            { label: "Open Source",              link: "/bab13/open-source/" },
            { label: "Portfolio",                link: "/bab13/portfolio/" },
            { label: "Belajar Git & GitHub",     link: "/bab13/belajar-git-github/" },
            { label: "Persiapan Magang",         link: "/bab13/persiapan-magang/" },
            { label: "Persiapan Karier",         link: "/bab13/persiapan-karier/" },
            { label: "Sertifikasi",              link: "/bab13/sertifikasi/" },
            { label: "Roadmap Belajar",          link: "/bab13/roadmap-belajar/" },
            { label: "Resources",                link: "/bab13/resources/" },
            { label: "Challenge",                link: "/bab13/challenge/" },
            { label: "Penutup",                  link: "/bab13/penutup/" },
          ],
        },
      ],
    }),
  ],
});


